# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f3a35aa9aa9bfbfd990f589b1825e0cfecf0db2caf1a1bbfd7c307d3dc06bcd353416f95bc16b151e015dd8e7e3b90134496889b2311a885687fb399bf16d57

test:
  secret_key_base: d064a554e3f94b3958fa24f8a87a554f8f58ebe0d5e76d12d4c12c08487d649bd434f17c206d8d1ee6d47ef182ffaa746c00bf986ceeca78d30034c48558dfd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
